Attempt at stream extensions and recording toggle
ystv/ffmpeg-scripts pull request #1
Opened 2021-04-27 11:14 UTC by cs-499243

Allows a -r flag to enable recording (off by default) and an argument to change where the stream is directed to. Instructions slightly unclear so this is not final

2021-04-27 15:43 UTC, rmil requested changes
Seems pretty good! Just need to have a nosey at my comments and I'll try and get a test to see it works

2021-04-27 15:43 UTC, rmil commented on stream-nvenc.sh
> +
I'd say split this variable into two; the base URL and then the default stream path?

2021-04-27 15:43 UTC, rmil commented on stream-nvenc.sh
> +                toFile="-vcodec pores -acodec copy "'"'"Recordings/${filename}.mov"'"'""
vcodec and acodec are the old ffmpeg ways to change the codec. If you swap it to: `-c:v prores -c:a copy` we'll be in business

2021-04-27 15:43 UTC, rmil commented on stream-nvenc.sh
> +echo " Starting event: $filename"
Perhaps, also explicitly indicate that it is recording?

2021-04-27 19:42 UTC, cs-endo commented on stream-nvenc.sh
> +
Can you give an example of what each could be?

2021-04-28 14:52 UTC, rmil commented on stream-nvenc.sh
> +
Something like:
```
rtmpServer="rtmp://stream.ystv.co.uk/"
defaultStream="internal/ob2"
```

2021-04-30 01:03 UTC, merged